name: Build and Deploy Vite React

on:
  push:
    branches:
      - main

concurrency:
  group: github-pages
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v6

      # Node.js installieren
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      # GitHub Pages vorbereiten
      - name: Setup Pages
        uses: actions/configure-pages@v6

      # Abhängigkeiten installieren
      - name: Install dependencies
        run: npm ci

      # Vite Build
      - name: Build project
        run: npm run build

      # docs als GitHub-Pages-Artefakt bereitstellen
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs

      # Auf GitHub Pages veröffentlichen
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4